name: Ansible Lint

on:
  push:
    branches:
      - master
      - main # Added main branch
    tags:
      - 'v*.*.*' # Added tags
  pull_request:
    branches:
      - master
      - main # Added main branch for PRs

jobs:
  lint:
    name: Run ansible-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Updated to v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Updated to v5
        with:
          python-version: '3.11' # Kept your specified Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint jmespath yamllint # Added yamllint

      - name: Run ansible-lint
        run: ansible-lint . # Added explicit path
